### ISSUE TITLE
not compatible with neovim

### ISSUE THREAD

**Issue by steveej** [tex/vimpreviewpandoc#4]
I'm trying to package this on NixOS and use it with neovim but so far my attempts are failing. I'm not familiar with the internals of (neo)vim plugins, so I'll just link you to my PR that demonstrates the issue:
https://github.com/NixOS/nixpkgs/pull/13575#issuecomment-190337596

**Comment by tex** [comment]
I already noticed it. It is caused by creating a thread in python. I have no idea how to fix it for neovim. Any help is appreciated.

**Comment by tex** [comment]
It looks more like a neovim error:

```
Exception in thread Thread-1:                                                         
Traceback (most recent call last):                                                    
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner              
    self.run()                                                                        
  File "<string>", line 199, in run                                                   
  File "<string>", line 183, in pandoc                                                
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 160, in write 
    self.redirect_handler(data)                                                       
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 58, in <lambda
>                                                                                     
    sys.stderr = RedirectStream(lambda data: nvim.err_write(data))                    
  File "/usr/lib/python2.7/site-packages/neovim/api/nvim.py", line 209, in err_write  
    return self._session.request('vim_err_write', msg)                                
  File "/usr/lib/python2.7/site-packages/neovim/api/common.py", line 230, in request  
    return walk(self._in, self._session.request(name, *args, **kwargs),               
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 81, in r
equest                                                                                
    v = self._yielding_request(method, args)                                          
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 146, in 
_yielding_request                                                                     
    return parent.switch()                                                            
AttributeError: 'NoneType' object has no attribute 'switch'                           
```

**Comment by tex** [comment]
My plugin creates a thread in python, the thread does I/O (executes pandoc with popen, writes to its stdin, reads from stdout, stderr). Thread does not return anything back to vim.

**Comment by tex** [comment]
Reported at https://github.com/neovim/neovim/issues/4385

**Comment by tex** [comment]
Fixed the problem and I'll push tommorow.

**Comment by steveej** [comment]
That's great news, thanks! I'll try it as soon as you've pushed it.

**Comment by tex** [comment]
Pushed. Please try it and if it is ok then close this. Thanks!

**Comment by steveej** [comment]
I can open markdown files with the plugin loaded, and I can manually use `:call vimpreviewpandoc#VimPreviewPandocConvertTo("html")` and can see and open the html fine.

After I run `:Pandoc` the plugin goes active, but as soon as it tries to update the browser (firefox in my case), the following exception occurs:

```
Exception in thread Thread-4:                                                                                                                  
Traceback (most recent call last):                                                                                                             
  File "/nix/store/pg4bgn41jhhpsqjgbvipdkv9an0g7q0g-python-2.7.11-env/lib/python2.7/threading.py", line 801, in __bootstrap_inner              
    self.run()                                                                                                                                 
  File "<string>", line 200, in run                                                                                                            
TypeError: __call__() takes exactly 3 arguments (4 given)                                                                                      
Press ENTER or type command to continue                                                                                                        
Unhandled exception in thread started by <bound method PreviewThread.__bootstrap of <PreviewThread(Thread-4, stopped 140173739857664)>>        
```

**Comment by steveej** [comment]
Another issue I've found is that it won't render anymore when a blockdiag section is in the markdown file. There's no error message though.

**Comment by tex** [comment]
Try now please.

**Comment by tex** [comment]
BTW: My plugin does not provide nor require executing :Pandoc 
It should automatically show output on Konqueror / Firefox with that plugin and static/index.html opened...

**Comment by steveej** [comment]
I'm trying this out right now but I can't find the _index.html_ file anywhere. What steps exactly should be required after opening the markdown file?

**Comment by tex** [comment]
The index.html is in this plugin : static/index.html. You have to point your firefox to folder where this plugin is installed in to file static/index.html.

In konqueror it is much easier as it allows to remotely change url.

**Comment by steveej** [comment]
Oh I see. Could you possibly introduce an "xdg-open" command to open this file? That way one could delegate that to firefox. It's not trivial to find it on NixOS, especially with multiple generations of the plugin existing in the filesystem.

Opening multiple vim's get's to a point where vim simply hangs on startup and there is no way to repair it unless I reboot the whole machine, which is really weird and annoying at the same time.

**Comment by steveej** [comment]
While I've got some other questions the original issue is resolved, thanks to you!
